### ISSUE TITLE
System Schema

### ISSUE THREAD

**Issue by z64** [z64/traikoa#4]
## Schema

key | type | description
---|---|---
id|UInt64|system id
name|String|system name
position|Array(Float64)|system position, in light years
allegiance|String|system allegiance
economy|String|economy type
government|String|government type
security|String|security level

## Sample

```json
{
  "id": 1,
  "name": "example system",
  "position": [0.25, -0.5, 21.1],
  "allegiance": "Independant",
  "economy": "High Tech",
  "government": "Democracy",
  "security_level": "Low"
}
```

**Comment by z64** [comment]
## Position Key

**Should this be:**
1. A single key with the value of `Array(Float64)`, i.e. `"position": [0.05, 1.5, -20.231]`
2. A single key with a *position object,* i.e. `"position": {"x": 0.05, "y": 1.5, "z": -20.231}`
3. Three top level keys of `x`, `y`, and `z` respectively

**Comment by z64** [comment]
## Factions & Faction Presences, Stations

I figure it might come up, so I'll address here: for each of these items, I believe it will be best if we store them as their own schemas and joined later with foreign keys instead of having a singular system object with a bunch of nested properties.

**Note that this applies internally, inside the database. We may build & serve such a nested object in the API endpoints, see #7**

These schemas will have their own issues, but briefly:

- A Faction resource would have the factions metadata (name, government type, etc.) and a FK to its home system if known / desirable - though I don't think this is exposed anywhere.
- A Faction Presence resource would have an FK to the Faction and another FK to the System to create the relationship. It would additionally have presence-specific data such as `influence`.
- Stations would have an FK to the system they belong to, and related system data. This will be discussed & expanded upon in #2 and later when we design support for markets, shipyard, and outfitting.

**Comment by z64** [comment]
## ID Key

RethinkDB gives each object an `id` key with a unique string value. 

Example: ` { ..."id": "4cBJ9xQwfXfGPE" ... }`

This is nice because it will hinder people trying to scrape our API, rather than if we had used an integer index instead it would be easy just to roll through IDs to get every object (unless they had been deleted / moved of course, but this is very low probability their request will fail). So I would be happy to directly expose this.

The downside is that if we create a bulk-fetch endpoint for getting multiple systems (which I would like to do for each resource) is that querystrings might get unruly. However I don't think this is really a "problem".

**Comment by Reaver01** [comment]
## Position Key  
`"position": [0.05, 1.5, -20.231]` works just fine in my opinion.  It follows an already established coordinate system `(x, y, z)`.  
"The Cartesian coordinates of a point are usually written in parentheses and separated by commas, as in (10, 5) or (3, 5, 7). The origin is often labelled with the capital letter O. In analytic geometry, unknown or generic coordinates are often denoted by the letters (x, y) in the plane, and (x, y, z) in three-dimensional space." (https://en.wikipedia.org/wiki/Cartesian_coordinate_system)

## Factions & Faction Presences, Stations  
These should be stored as schemas with foreign keys.  I think it just makes for a much cleaner database and saves having to make database wide changes when a schema needs a change.

## ID Key  
RethinkDB's way of assigning unique string values is perferable.  I can't find any reason that we would want them to be integers.

**Comment by z64** [comment]
Besides also switching from rethink to postgres, I'll close this now (pending later refinement of the schema later probably) with b1e29d1b689eae5a0fbd14c17749c5332762fae3
